# Generated by Django 4.0.6 on 2022-08-14 11:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favicon',
            fields=[
                ('id', models.CharField(max_length=500, primary_key=True, serialize=False)),
                ('source_url', models.URLField(default=None, null=True)),
                ('destination_url', models.URLField(default=None, null=True)),
                ('size', models.IntegerField(default=None, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
