# Generated by Django 4.0.6 on 2022-08-11 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faviconer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='favicon',
            name='destination_url',
            field=models.URLField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='favicon',
            name='size',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='favicon',
            name='source_url',
            field=models.URLField(default=None, null=True),
        ),
    ]
