# Generated by Django 4.0.6 on 2022-08-14 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faviconer', '0002_favicon_destination_url_favicon_size_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Favicon',
        ),
    ]
